[workspace]
members = [
    "crates/stata-sys",
    "."
]

[package]
name = "stata_parquet_io"
version = "1.7.2"
authors = ["Jon Rothbaum <jlrothbaum@gmail.com>"]
edition = "2021"
description = "Stata plugin to read/write parquet files using polars Rust"
license = "MIT"
default-run = "stata_parquet_io"
repository = "https://github.com/jrothbaum/stata_parquet_io"
build = "build.rs" 

[lib]
name = "stata_parquet_io"
crate-type= ["cdylib"]

[dependencies]
polars = { version = "0.49.1", features=["lazy",
    "parquet",
    # "streaming",
    "dtype-categorical",
    "dtype-i8",
    "dtype-i16",
    "dtype-u8",
    "dtype-u16",
] }
polars-sql = "0.49.1" 

stata-sys = { path = "./crates/stata-sys" }
rayon = "1.8"
log = "0.4"
env_logger = "0.11.8"
serde = "1.0.219"
serde_json = "1.0.141"
glob = "0.3"
regex = "1.0"

[profile.release]
strip = "symbols"  # Remove debug info but keep symbols needed for performance
panic = "unwind"     # Default panic behavior (often better for libraries)
lto = "fat"         # More aggressive link-time optimization for speed
codegen-units = 1   # Fewer codegen units allow more optimization

[profile.dev]
split-debuginfo = "packed"
strip = "symbols"
