name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: write
  issues: read
  pull-requests: read
jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows",
              os: windows-latest,
              target: "x86_64-pc-windows-msvc",
              extension: "dll",
              platform_name: "windows"
            }
          - {
              name: "macOS Universal",
              os: macos-latest,
              target: "universal",
              extension: "dylib",
              platform_name: "macos"
            }
          - {
              name: "Linux",
              os: ubuntu-latest,
              target: "x86_64-unknown-linux-gnu",
              extension: "so",
              platform_name: "linux"
            }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Windows C++ environment
        if: matrix.config.platform_name == 'windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up macOS C++ environment
        if: matrix.config.platform_name == 'macos'
        run: |
          xcode-select --install || true
          echo "MACOSX_DEPLOYMENT_TARGET=10.13" >> $GITHUB_ENV

      - name: Install Rust toolchain (non-Linux)
        if: matrix.config.platform_name != 'linux'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.platform_name == 'macos' && 'x86_64-apple-darwin,aarch64-apple-darwin' || matrix.config.target }}
          components: rustfmt, clippy

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.config.target }}

      - name: Set platform-specific environment
        shell: bash
        run: |
          if [ "${{ matrix.config.platform_name }}" = "windows" ]; then
            echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          elif [ "${{ matrix.config.platform_name }}" = "macos" ]; then
            true
          fi

      - name: Display build configuration
        run: |
          ls -la
          if [ -f "build.rs" ]; then
            echo "Custom build script found"
            cat build.rs
          fi
        shell: bash

      - name: Build release (Linux)
        if: matrix.config.platform_name == 'linux'
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace almalinux:8 bash -c "
            set -ex
            # Install basic build tools and repos
            dnf install -y gcc gcc-c++ make cmake curl wget git epel-release
            
            # Install LLVM and Clang
            dnf install -y clang-devel llvm-devel
            
            # Find libclang path and set environment variables
            export LIBCLANG_PATH=\$(find /usr/lib64 /usr/lib -name \"libclang.so*\" | head -n 1 | xargs dirname)
            export LD_LIBRARY_PATH=\${LIBCLANG_PATH}:\${LD_LIBRARY_PATH}
            
            # Install Rust
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source \$HOME/.cargo/env
            
            # Build your project
            rustup target add x86_64-unknown-linux-gnu
            cargo build --release --target x86_64-unknown-linux-gnu
          "

      - name: Build release (macOS Universal)
        if: matrix.config.platform_name == 'macos'
        run: |
          # Build for x86_64 (Intel)
          cargo build --release --target x86_64-apple-darwin
          
          # Build for aarch64 (ARM)
          cargo build --release --target aarch64-apple-darwin
          
          # Create universal binary
          mkdir -p target/universal-apple-darwin/release
          lipo -create \
            target/x86_64-apple-darwin/release/libstata_parquet_io.dylib \
            target/aarch64-apple-darwin/release/libstata_parquet_io.dylib \
            -output target/universal-apple-darwin/release/libstata_parquet_io.dylib
          
          # Verify the universal binary
          echo "Universal binary architecture info:"
          lipo -info target/universal-apple-darwin/release/libstata_parquet_io.dylib
        env:
          RUST_BACKTRACE: 1
          POLARS_STATICALLY_LINK: 1
          OPENSSL_STATIC: 1
          CARGO_FEATURE_VENDORED: 1

      - name: Build release (non-Linux, non-macOS)
        if: matrix.config.platform_name != 'linux' && matrix.config.platform_name != 'macos'
        run: cargo build --release --target ${{ matrix.config.target }}
        env:
          RUST_BACKTRACE: 1
          POLARS_STATICALLY_LINK: 1
          OPENSSL_STATIC: 1
          CARGO_FEATURE_VENDORED: 1

      - name: Prepare release files
        shell: bash
        run: |
          mkdir -p release_package

          if [ "${{ matrix.config.platform_name }}" = "windows" ]; then
            cp target/${{ matrix.config.target }}/release/stata_parquet_io.${{ matrix.config.extension }} release_package/pq.${{ matrix.config.extension }}
          elif [ "${{ matrix.config.platform_name }}" = "macos" ]; then
            # Use the universal binary
            cp target/universal-apple-darwin/release/libstata_parquet_io.${{ matrix.config.extension }} release_package/pq.${{ matrix.config.extension }}
            
            echo "Universal binary verification:"
            lipo -info release_package/pq.${{ matrix.config.extension }}
          elif [ "${{ matrix.config.platform_name }}" = "linux" ]; then
            if [ -f "target/${{ matrix.config.target }}/release/libstata_parquet_io.${{ matrix.config.extension }}" ]; then
              cp target/${{ matrix.config.target }}/release/libstata_parquet_io.${{ matrix.config.extension }} release_package/pq.${{ matrix.config.extension }}
            elif [ -f "target/${{ matrix.config.target }}/release/stata_parquet_io.${{ matrix.config.extension }}" ]; then
              cp target/${{ matrix.config.target }}/release/stata_parquet_io.${{ matrix.config.extension }} release_package/pq.${{ matrix.config.extension }}
            else
              echo "Error: Could not find the expected library file."
              ls -la target/${{ matrix.config.target }}/release/
              exit 1
            fi

            echo "Checking library dependencies:"
            ldd release_package/pq.${{ matrix.config.extension }} || echo "ldd unavailable"
          fi

          cp src/ado/p/pq.ado release_package/
          cp src/ado/p/pq.pkg release_package/
          cp src/ado/p/pq.sthlp release_package/

          echo "Files in release package:"
          ls -la release_package/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pq-${{ matrix.config.platform_name }}
          path: release_package/
          retention-days: 7

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: ls -R

      - name: Create platform zip files
        run: |
          cd pq-windows && zip -r ../pq-windows.zip * && cd ..
          cd pq-macos && zip -r ../pq-macos.zip * && cd ..
          cd pq-linux && zip -r ../pq-linux.zip * && cd ..
      - name: Create SSC package zip
        run: |
          mkdir -p pq-ssc
          
          # Copy Stata files from any platform (they're identical)
          cp pq-windows/pq.ado pq-ssc/
          cp pq-windows/pq.sthlp pq-ssc/
          cp pq-windows/pq.pkg pq-ssc/
          
          # Copy platform-specific binaries
          cp pq-windows/pq.dll pq-ssc/
          cp pq-macos/pq.dylib pq-ssc/
          cp pq-linux/pq.so pq-ssc/
          
          # Verify contents
          echo "SSC package contents:"
          ls -la pq-ssc/
          
          # Create zip
          cd pq-ssc && zip -r ../pq-ssc.zip * && cd ..
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pq-windows.zip
            pq-macos.zip
            pq-linux.zip
            pq-ssc.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}